/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.daniel.aplikasi.view;

import edu.daniel.aplikasi.fungsi.Sequel;
import edu.daniel.aplikasi.fungsi.Koneksi;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author DANIELFRANS
 */
public class FrmOrder extends javax.swing.JFrame {

    Connection conn = Koneksi.getConnection();
    ResultSet rs = null;
    PreparedStatement pst = null;

    private final Sequel sql = new Sequel();

    int userID = User.getUserID();

    DecimalFormat kursIndonesia;
    DecimalFormatSymbols formatRupiah;

    /**
     * Creates new form FormTambahTransaksi
     */
    public FrmOrder() {
        initComponents();
        sql.autoNumberOrder();
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = formatter.format(date);
        txtTanggalOrder2.setText(tgl);
        String namaPaket = cmbJenisPaket2.getSelectedItem().toString();
        sql.showNoLabelPaket(namaPaket);

        jTableOrderDetail.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 12));
        jTableOrderDetail.getTableHeader().setOpaque(false);
        jTableOrderDetail.getTableHeader().setBackground(new Color(32, 136, 203));
        jTableOrderDetail.getTableHeader().setForeground(new Color(255, 255, 255));

    }

    public void filterHuruf(KeyEvent a) {
        if (Character.isDigit(a.getKeyChar())) {
            a.consume();
            JOptionPane.showMessageDialog(null, "Masukkan hanya Huruf", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void filterAngka(KeyEvent b) {
        if (Character.isAlphabetic(b.getKeyChar())) {
            b.consume();
            JOptionPane.showMessageDialog(null, "Masukkan hanya Angka", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void resetOrder() {
        labelNoPaket2.setText("");
//        labelNamaPelanggan2.setText("");
        cmbJenisPaket2.setSelectedItem(0);
        txtBerat2.setText("");
        txtHarga2.setText("");
        txtSubTotal2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnGenerateHarga = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        btnHitungSubTotal = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnTambahOrder = new javax.swing.JButton();
        btnUbahOrder = new javax.swing.JButton();
        btnHapusOrder = new javax.swing.JButton();
        btnBatalOrder = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        dummyField.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cucian Masuk");
        setAutoRequestFocus(false);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1022, 620));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtTanggalOrder2.setEditable(false);
        txtTanggalOrder2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        labelNamaPelanggan2.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        txtStatusPengerjaan2.setEditable(false);
        txtStatusPengerjaan2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtStatusPengerjaan2.setText("proses");

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel12.setText("Sub Total");

        txtBerat2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtBerat2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBerat2KeyTyped(evt);
            }
        });

        txtNoOrder2.setEditable(false);
        txtNoOrder2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Nama Paket");

        labelCountOrder.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        labelCountOrder.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton1.setText("Daftar Pelanggan");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("No Pelanggan");

        btnGenerateHarga.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btnGenerateHarga.setText("Generate");
        btnGenerateHarga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGenerateHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateHargaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel1.setText("No Order");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Berat");

        labelNoPaket2.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N

        txtHarga2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtHarga2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHarga2KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("Status Pengerjaan");

        jTableOrderDetail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableOrderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableOrderDetail.setGridColor(new java.awt.Color(255, 255, 255));
        jTableOrderDetail.setIntercellSpacing(new java.awt.Dimension(8, 5));
        jTableOrderDetail.setRowHeight(25);
        jTableOrderDetail.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTableOrderDetail.setShowHorizontalLines(false);
        jTableOrderDetail.setShowVerticalLines(false);
        jTableOrderDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOrderDetailMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableOrderDetail);

        labelTotalHarga.setBackground(new java.awt.Color(0, 0, 0));
        labelTotalHarga.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        labelTotalHarga.setForeground(new java.awt.Color(255, 0, 0));
        labelTotalHarga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotalHarga.setText("0");
        labelTotalHarga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelTotalHarga.setOpaque(true);

        txtNoPelanggan2.setEditable(false);
        txtNoPelanggan2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNoPelanggan2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtNoPelanggan2CaretUpdate(evt);
            }
        });

        btnHitungSubTotal.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btnHitungSubTotal.setText("Hitung");
        btnHitungSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnHitungSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungSubTotalActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 30)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cucian Masuk");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setOpaque(true);

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Tanggal");

        txtSubTotal2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtSubTotal2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSubTotal2KeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Harga");

        cmbJenisPaket2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cmbJenisPaket2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJenisPaket2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTambahOrder.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btnTambahOrder.setText("Simpan");
        btnTambahOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTambahOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahOrderActionPerformed(evt);
            }
        });

        btnUbahOrder.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btnUbahOrder.setText("Ubah");
        btnUbahOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnUbahOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahOrderActionPerformed(evt);
            }
        });

        btnHapusOrder.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btnHapusOrder.setText("Hapus");
        btnHapusOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnHapusOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusOrderActionPerformed(evt);
            }
        });

        btnBatalOrder.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btnBatalOrder.setText("Batal");
        btnBatalOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBatalOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalOrderActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambahOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnUbahOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapusOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBatalOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbahOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatalOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCountOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtBerat2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                            .addComponent(txtNoOrder2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                            .addComponent(txtNoPelanggan2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                                        .addComponent(cmbJenisPaket2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelNamaPelanggan2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(7, 7, 7)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(labelNoPaket2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(btnGenerateHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSubTotal2)
                                        .addComponent(txtTanggalOrder2)
                                        .addComponent(txtStatusPengerjaan2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                                    .addGap(20, 20, 20)
                                    .addComponent(btnHitungSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE))
                        .addComponent(jScrollPane2)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelTotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBerat2, txtNoOrder2, txtNoPelanggan2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(labelTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNoOrder2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNoPelanggan2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtStatusPengerjaan2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(labelNamaPelanggan2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbJenisPaket2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenerateHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNoPaket2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBerat2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHitungSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTanggalOrder2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(labelCountOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel12, jLabel5, jLabel8, txtHarga2, txtStatusPengerjaan2, txtSubTotal2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel7, txtBerat2, txtNoOrder2, txtNoPelanggan2, txtTanggalOrder2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnGenerateHarga, btnHitungSubTotal});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateHargaActionPerformed
        // TODO add your handling code here:
        String namaPaket = cmbJenisPaket2.getSelectedItem().toString();
        sql.showHarga(namaPaket);
    }//GEN-LAST:event_btnGenerateHargaActionPerformed

    private void btnHitungSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungSubTotalActionPerformed
        // TODO add your handling code here:

        if (!"".equals(txtBerat2.getText())
                && !"".equals(txtHarga2.getText())) {
            int berat = Integer.parseInt(txtBerat2.getText());
            int harga = Integer.parseInt(txtHarga2.getText());
            int subTotal = berat * harga;
            txtSubTotal2.setText(Integer.toString(subTotal));
        } else {
            JOptionPane.showMessageDialog(null, "Anda harus mengisi data dengan lengkap", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnHitungSubTotalActionPerformed

    private void jTableOrderDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOrderDetailMouseClicked
        // TODO add your handling code here:
        int baris = jTableOrderDetail.getSelectedRow();

        txtNoOrder2.setText(jTableOrderDetail.getValueAt(baris, 0).toString());
        labelNoPaket2.setText(jTableOrderDetail.getValueAt(baris, 1).toString());
        cmbJenisPaket2.setSelectedItem(jTableOrderDetail.getValueAt(baris, 2).toString());
        txtBerat2.setText(jTableOrderDetail.getValueAt(baris, 3).toString());
        txtHarga2.setText(jTableOrderDetail.getValueAt(baris, 4).toString());
        txtSubTotal2.setText(jTableOrderDetail.getValueAt(baris, 5).toString());

    }//GEN-LAST:event_jTableOrderDetailMouseClicked

    private void txtHarga2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHarga2KeyTyped
        // TODO add your handling code here:
        filterAngka(evt);
        if (txtHarga2.getText().length() == 9) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Maksimal yang dimasukkan hanya 9 Karakter", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtHarga2KeyTyped

    private void txtSubTotal2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubTotal2KeyTyped
        // TODO add your handling code here:
        filterAngka(evt);
        if (txtSubTotal2.getText().length() == 9) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Maksimal yang dimasukkan hanya 9 Karakter", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtSubTotal2KeyTyped

    private void txtBerat2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBerat2KeyTyped
        // TODO add your handling code here:
        filterAngka(evt);
        if (txtBerat2.getText().length() == 3) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Maksimal yang dimasukkan hanya 3 Karakter", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtBerat2KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new FrmPelanggan().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNoPelanggan2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtNoPelanggan2CaretUpdate
        // TODO add your handling code here:
        String noPelanggan = txtNoPelanggan2.getText();
        sql.showNoPelanggan(noPelanggan);
    }//GEN-LAST:event_txtNoPelanggan2CaretUpdate

    private void cmbJenisPaket2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJenisPaket2ActionPerformed
        // TODO add your handling code here:
        if (cmbJenisPaket2.getSelectedIndex() != -1) {
            String namaPaket = cmbJenisPaket2.getSelectedItem().toString();
            sql.showNoLabelPaket(namaPaket);
        }
    }//GEN-LAST:event_cmbJenisPaket2ActionPerformed

    private void btnHapusOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusOrderActionPerformed
        // TODO add your handling code here:

        if (!"".equals(txtNoOrder2.getText())
                && !"".equals(cmbJenisPaket2.getSelectedItem())
                && !"".equals(labelNoPaket2.getText())) {
            String noOrder = txtNoOrder2.getText();
            String noPaket = labelNoPaket2.getText();
            sql.hapusOrder(noPaket);
            sql.showOrder2(noOrder);
            sql.totalHarga(noOrder);
            resetOrder();
        } else {
            JOptionPane.showMessageDialog(null, "Anda harus mengisi data dengan lengkap", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusOrderActionPerformed

    private void btnUbahOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahOrderActionPerformed
        // TODO add your handling code here:

        if (!"".equals(txtNoOrder2.getText())
                && !"".equals(txtNoPelanggan2.getText())
                && !"".equals(cmbJenisPaket2.getSelectedItem())
                && !"".equals(labelNoPaket2.getText())
                && !"".equals(txtBerat2.getText())
                && !"".equals(txtHarga2.getText())
                && !"".equals(txtSubTotal2.getText())) {
            String noOrder = txtNoOrder2.getText();
            String noPaket = labelNoPaket2.getText();
            String jenis = cmbJenisPaket2.getSelectedItem().toString();
            int berat = Integer.parseInt(txtBerat2.getText());
            int harga = Integer.parseInt(txtHarga2.getText());
            int subTotal = Integer.parseInt(txtSubTotal2.getText());
            sql.ubahOrder(noOrder, noPaket, jenis, berat, harga, subTotal);
            sql.showOrder2(noOrder);
            sql.totalHarga(noOrder);
            resetOrder();
        } else {
            JOptionPane.showMessageDialog(null, "Anda harus mengisi data dengan lengkap", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUbahOrderActionPerformed

    private void btnTambahOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahOrderActionPerformed
        // TODO add your handling code here:

        if (!"".equals(txtNoOrder2.getText())
                && !"".equals(txtNoPelanggan2.getText())
                && !"".equals(labelNamaPelanggan2.getText())
                && !"".equals(cmbJenisPaket2.getSelectedItem())
                && !"".equals(labelNoPaket2.getText())
                && !"".equals(txtBerat2.getText())
                && !"".equals(txtHarga2.getText())
                && !"".equals(txtSubTotal2.getText())) {
            String noOrder = txtNoOrder2.getText();
            String noPelanggan = txtNoPelanggan2.getText();
            String namaPelanggan = labelNamaPelanggan2.getText();
            String tglOrder = txtTanggalOrder2.getText();
            String status = txtStatusPengerjaan2.getText();
            String noPaket = labelNoPaket2.getText();
            String jenis = cmbJenisPaket2.getSelectedItem().toString();
            int berat = Integer.parseInt(txtBerat2.getText());
            int harga = Integer.parseInt(txtHarga2.getText());
            int subTotal = Integer.parseInt(txtSubTotal2.getText());

            if (sql.isOrderExists(noOrder)) {
                sql.simpanOrderDetail(noOrder, noPaket, jenis, berat, harga, subTotal);
                sql.showOrder2(noOrder);
                sql.totalHarga(noOrder);
                resetOrder();
            } else {
                resetOrder();
                sql.simpanOrder(noOrder, noPelanggan, namaPelanggan, tglOrder, status);
                sql.simpanOrderDetail(noOrder, noPaket, jenis, berat, harga, subTotal);
                sql.showOrder2(noOrder);
                sql.totalHarga(noOrder);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Anda harus mengisi data dengan lengkap", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahOrderActionPerformed

    private void btnBatalOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalOrderActionPerformed
        // TODO add your handling code here:

        if (!"".equals(txtNoOrder2.getText())) {
            String noOrder = txtNoOrder2.getText();
            sql.batalOrder(noOrder);
            sql.showOrder2(noOrder);
            sql.totalHarga(noOrder);
            resetOrder();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Anda harus mengisi data dengan lengkap", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBatalOrderActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        resetOrder();
        sql.autoNumberOrder();
        cmbJenisPaket2.removeAllItems();
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalOrder;
    private javax.swing.JButton btnGenerateHarga;
    private javax.swing.JButton btnHapusOrder;
    private javax.swing.JButton btnHitungSubTotal;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambahOrder;
    private javax.swing.JButton btnUbahOrder;
    public static final javax.swing.JComboBox<String> cmbJenisPaket2 = new javax.swing.JComboBox<>();
    public static final javax.swing.JTextField dummyField = new javax.swing.JTextField();
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public static final javax.swing.JTable jTableOrderDetail = new javax.swing.JTable();
    public static final javax.swing.JLabel labelCountOrder = new javax.swing.JLabel();
    public static final javax.swing.JLabel labelNamaPelanggan2 = new javax.swing.JLabel();
    public static final javax.swing.JLabel labelNoPaket2 = new javax.swing.JLabel();
    public static final javax.swing.JLabel labelTotalHarga = new javax.swing.JLabel();
    public static final javax.swing.JTextField txtBerat2 = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtHarga2 = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtNoOrder2 = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtNoPelanggan2 = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtStatusPengerjaan2 = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtSubTotal2 = new javax.swing.JTextField();
    public static final javax.swing.JTextField txtTanggalOrder2 = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
